### PR TITLE
Lines starting with # are treated as comments

### PR DESCRIPTION
**Pull request by moisesbr-dw**
Simple enhancement to permit comments within "explain.conf".
When this file has many lines, comments are useful to introduce groups of related entries.

### CODE REVIEW

**Comment by moisesbr-dw** [comment]
The wiki page at "plugin:explain" should be updated if this pull request is merged.

**Comment by splitbrain** [comment]
thanks for the PR. can you please update the docs?

**Comment by moisesbr-dw** [comment]
Sure. Could you up the plugin version?

**Comment by moisesbr-dw** [comment]
Page "plugin:explain" updated.

**Pull request merged**
